name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: pnpm

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yarn/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yarn/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright Browsers
        run: yarn playwright-core install chromium
      - name: Run tests
        run: yarn run test
